# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1607, 910)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(20, 30, 1381, 851))
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(1430, 720, 151, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.visualize = QtWidgets.QPushButton(self.layoutWidget)
        self.visualize.setObjectName("visualize")
        self.verticalLayout_3.addWidget(self.visualize)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(1430, 40, 151, 51))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(1430, 482, 151, 41))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalSlider = QtWidgets.QSlider(self.widget1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_5.addWidget(self.horizontalSlider)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(1430, 610, 151, 51))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.widget3 = QtWidgets.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(1430, 140, 151, 51))
        self.widget3.setObjectName("widget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.algo = QtWidgets.QLabel(self.widget3)
        self.algo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.algo.setAlignment(QtCore.Qt.AlignCenter)
        self.algo.setObjectName("algo")
        self.verticalLayout.addWidget(self.algo)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(5, "")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.widget4 = QtWidgets.QWidget(Dialog)
        self.widget4.setGeometry(QtCore.QRect(1430, 280, 151, 121))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.clear = QtWidgets.QPushButton(self.widget4)
        self.clear.setObjectName("clear")
        self.verticalLayout_6.addWidget(self.clear)
        self.pushButton = QtWidgets.QPushButton(self.widget4)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PATH VISUALIZER"))
        self.visualize.setText(_translate("Dialog", "VISUALIZE"))
        self.label.setText(_translate("Dialog", "SELECT NODE"))
        self.comboBox.setItemText(0, _translate("Dialog", " Start Node"))
        self.comboBox.setItemText(1, _translate("Dialog", "Target Node"))
        self.comboBox.setItemText(2, _translate("Dialog", "Bomb Node(Diffuse me first)"))
        self.comboBox.setItemText(3, _translate("Dialog", "Weight Node"))
        self.label_3.setText(_translate("Dialog", "VISUALIZATION SPEED"))
        self.label_2.setText(_translate("Dialog", "CURRENT NODE"))
        self.algo.setText(_translate("Dialog", " ALGORITHMS"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Breadth First Search"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Depth First Search"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Dijkstra\'s Algorithm"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Floyd Warshall Algorithm"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "A* Algorithm"))
        self.clear.setText(_translate("Dialog", "CLEAR BOARD"))
        self.pushButton.setText(_translate("Dialog", "CLEAR WEIGHT AND BLOCK"))
        self.pushButton_2.setText(_translate("Dialog", "CLEAR PATH"))

